### ISSUE TITLE
Driver 1.6.0.89 does not compile under RHEL 7 (3.10.0-514.el7.x86_64)

### ISSUE THREAD

**Issue by dmesser** [diablotech/teradimm-driver#1]
cat /etc/redhat-release
   Red Hat Enterprise Linux Server release 7.3 (Maipo)

uname -r
   3.10.0-514.el7.x86_64

make -C linux
   ...
  CC [M]  /root/setup/teradimm-driver/linux/driver/td_scan_asl.o
/root/setup/teradimm-driver/linux/driver/td_scan_asl.c: In function ‘td_scan_extract_address64’:
/root/setup/teradimm-driver/linux/driver/td_scan_asl.c:338:14: error: ‘struct acpi_resource_address64’ has no member named ‘address_length’
    (address64.address_length == 0)) {
              ^
/root/setup/teradimm-driver/linux/driver/td_scan_asl.c:343:27: error: ‘struct acpi_resource_address64’ has no member named ‘address_length’
  td_info->size = address64.address_length;
                           ^
/root/setup/teradimm-driver/linux/driver/td_scan_asl.c:344:29: error: ‘struct acpi_resource_address64’ has no member named ‘minimum’
  td_info->offset = address64.minimum;
                             ^
make[4]: *** [/root/setup/teradimm-driver/linux/driver/td_scan_asl.o] Error 1
make[3]: *** [_module_/root/setup/teradimm-driver/linux/driver] Error 2
make[3]: Leaving directory `/usr/src/kernels/3.10.0-514.el7.x86_64'
make[2]: *** [teradimm.ko] Error 2
make[2]: Leaving directory `/root/setup/teradimm-driver/linux/driver'
make[1]: *** [driver/all] Error 2
make[1]: Leaving directory `/root/setup/teradimm-driver/linux'
make: *** [do-all] Error 2
make: Leaving directory `/root/setup/teradimm-driver/linux'`

**Comment by jmendo5x** [comment]
Sysinfo could help to know this issue

**Comment by dwainsims** [comment]
I am having the same issue.  Is there a workaround?

**Comment by dwainsims** [comment]
I have the workaround.

This is the issue.  There is a file that is part of the RHEL 7.3 (.514) kernel called acrestyp.h, in the /include/acpi directory.  The file that is on the DVD/iso  has a bug; it is missing a structure definition for stuct acpi_resource_address64.  Once I got an updated acrestyp.h that had this structure defined, the build went as normal.  

The system I was building on was in a lab that had no connection to the internet, so it was straight RHEL 7.3.  If the system had been updated, it is likely that the acrestyp.h file would have been corrected automatically.    

I am attaching the acrestyp.h file that I used to complete the build on RHEL 7.3.


[acrestyp.zip](https://github.com/diablotech/teradimm-driver/files/847762/acrestyp.zip)
